apiVersion: apps/v1 
kind: Deployment
metadata:
  name: deployment-gateway
spec:
  selector:
    matchLabels:
      app: deployment-pod-label-gateway
  template:
    metadata:
      labels:
        app: deployment-pod-label-gateway      
    spec:
      containers: 
      - name: gateway 
        image: javaboost2/java8gatewayservice:v01
        resources:
          requests:
            cpu: "300m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "2048Mi"
        ports: 
        - containerPort: 80
        env:
          - name: CONFIG_SERVER_URL
            value: http://192.168.131.69:8888

        

        

