apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-gateway-export-ip
spec:
  selector:
    app: deployment-pod-label-gateway 
  type: LoadBalancer
  ports:
    - name:  gatewayport
      port: 80
      targetPort: 80