server:
  servlet:
    session:
      timeout: 120
  port: 9092

spring:
  security:
    user:
      name: muhammet
      password: 12345
  rabbitmq:
    host: localhost
    port: 5672
    username: bilgejava8
    password: bilgeadmin*
  cloud:
    compatibility-verifier:
      enabled: false
  zipkin:
    enabled: false
    base-url: http://localhost:9411
    service:
      name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sosyalmedyadb
      username: bilgeadmin
      password: bilge33**

#myapplication:
#  redis:
#    host: ${REDIS_HOST}
#    port: ${REDIS_PORT}
